# Generated by Django 4.2.14 on 2024-11-23 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=datetime.datetime(2024, 11, 23, 5, 31, 4, 131484, tzinfo=datetime.timezone.utc))),
                ('study_stage', models.IntegerField(default=0)),
                ('repeating_today', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_rows', models.IntegerField(default=1)),
                ('num_cols', models.IntegerField(default=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.board')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardItem',
            fields=[
                ('genericitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flashcards.genericitem')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
            bases=('flashcards.genericitem',),
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_column', models.CharField(blank=True, max_length=300, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.table')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderRowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.table')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.course'),
        ),
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('genericitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flashcards.genericitem')),
                ('text', models.TextField(blank=True, null=True)),
                ('table_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.headerrowitem')),
                ('table_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.tablerow')),
            ],
            bases=('flashcards.genericitem',),
        ),
    ]
