# Generated by Django 4.2.14 on 2024-11-23 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericitem',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 5, 37, 55, 292215, tzinfo=datetime.timezone.utc)),
        ),
    ]
