# Generated by Django 4.2.14 on 2024-11-27 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_genericitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genericitem',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 6, 9, 19, 596375, tzinfo=datetime.timezone.utc)),
        ),
    ]
