# Generated by Django 4.2.14 on 2024-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_tableitem_active_alter_genericitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericitem',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
